import type { Env } from "../env";
import { fingerprint } from "../crypto";
import { ask, JevError, type JevAnswer, type JevConfig, type Question } from "../jev/client";
import type { Settings } from "../settings";
import type { Cluster } from "./cluster";
import type { Verdict } from "./policy";

export const INTENTS: Record<string, string> = {
  search_crawler: "A search engine indexing pages",
  ai_crawler: "An AI company collecting pages for training or answers",
  scraper: "Copying content, prices, or listings at scale",
  credential_stuffing: "Trying stolen usernames and passwords against login or account pages",
  vuln_scanner: "Probing for vulnerabilities, admin panels, or exposed files",
  monitor_or_load_test: "An uptime monitor, health check, or load test",
  partner_integration: "An integration, feed reader, or API client the site works with",
  human_burst: "Many real people arriving at once, for example from a link, newsletter, or launch",
};

const HARM_LEVELS = [
  "Harmless: no meaningful load and no attempt to misuse the site",
  "Minor: extra load the site can absorb, no misuse",
  "Noticeable: heavy load or bulk copying of public content",
  "Significant: probing for weaknesses, hammering expensive pages, or scraping at a scale that strains the site",
  "Severe: attacking accounts, exploiting vulnerabilities, or trying to take the site down",
];

/** The fixed questions every cluster is asked. Custom questions are added alongside them. */
export function buildQuestions(custom: Settings["jev"]["customQuestions"]): Record<string, Question> {
  const q: Record<string, Question> = {
    is_automated: {
      type: "noul",
      instructions: "Is the traffic described in `cluster` generated by automated software (bots, scripts, crawlers, scanners) rather than by people using web browsers?",
      criteria: {
        true: "Automated clients",
        false: "People browsing, even if many arrive at once, for example after a newsletter or a viral post",
      },
    },
    is_welcome: {
      type: "noul",
      instructions: "Is `cluster` most likely a service the owner of `site` would want to allow, such as a search engine crawler, an uptime monitor, a feed reader, or an integration the site relies on?",
    },
    intent: {
      type: "choice",
      instructions: "What is the traffic in `cluster` most likely trying to do on `site`?",
      criteria: INTENTS,
    },
    harm: {
      type: "score",
      instructions: "How much harm would the traffic in `cluster` do to `site` if it continued at this rate?",
      criteria: HARM_LEVELS,
    },
    action: {
      type: "choice",
      instructions: "What should the owner of `site` do about the traffic in `cluster` right now?",
      criteria: {
        allow: "Let it through; it is wanted or harmless",
        observe: "Keep watching; not clearly a problem yet",
        managed_challenge: "Ask visitors to prove they are human; real people pass easily",
        rate_limit: "Slow it down without stopping it",
        block: "Refuse it outright; clearly abusive",
      },
    },
  };
  for (const c of custom) {
    q[`custom_${c.id}`] = {
      type: "noul",
      instructions: c.instructions,
      ...(c.yes || c.no ? { criteria: { ...(c.yes ? { true: c.yes } : {}), ...(c.no ? { false: c.no } : {}) } } : {}),
    };
  }
  return q;
}

export async function buildState(secret: string, cluster: Cluster, site: { description: string; baselineRpm: number | null; currentRpm: number }) {
  // IPs and ranges are named by a salted hash: Jev sees behavior, never who the visitors were.
  const name =
    cluster.kind === "ip" || cluster.kind === "ip24"
      ? `${cluster.kind === "ip" ? "single_ip" : "ip_range"}:${await fingerprint(secret, cluster.target)}`
      : cluster.kind === "asn"
        ? `network:AS${cluster.target}`
        : cluster.kind === "ja4"
          ? `tls_fingerprint:${cluster.target}`
          : "user_agent";
  return {
    site: {
      description: site.description,
      normal_requests_per_minute: site.baselineRpm === null ? null : Math.round(site.baselineRpm),
      current_requests_per_minute: Math.round(site.currentRpm),
    },
    cluster: { grouped_by: name, ...cluster.features },
  };
}

export function toVerdict(answers: Record<string, JevAnswer>): Verdict {
  const noul = (k: string) => (answers[k]?.type === "noul" ? answers[k].noul : 0);
  const harm = answers.harm?.type === "score" ? answers.harm.score / (HARM_LEVELS.length - 1) : 0;
  return {
    pAutomated: noul("is_automated"),
    pWelcome: noul("is_welcome"),
    harm: Math.max(0, Math.min(1, harm)),
    intent: answers.intent?.type === "choice" ? answers.intent.choice : "unknown",
    advisedAction: answers.action?.type === "choice" ? answers.action.choice : "unknown",
    custom: Object.entries(answers)
      .filter(([k, a]) => k.startsWith("custom_") && a.type === "noul")
      .map(([k, a]) => ({ id: k.slice(7), p: (a as { noul: number }).noul })),
  };
}

export type JudgeOutcome =
  | { source: "jev" | "cache"; answers: Record<string, JevAnswer>; verdict: Verdict; model?: string }
  | { source: "rules"; why: string };

interface Budget {
  callsLeftThisTick: number;
}

const today = () => new Date().toISOString().slice(0, 10);

/**
 * One Jev call per cluster, with verdicts cached by cluster fingerprint and hard daily caps.
 * Falls back to rules-only when a cap is hit or the call fails.
 */
export async function judge(
  env: Env,
  jev: JevConfig | null,
  zoneId: string,
  cluster: Cluster,
  state: unknown,
  settings: Settings,
  budget: Budget,
  cacheTtl: number,
): Promise<JudgeOutcome> {
  const fp = await fingerprint(env.SPIKEWARD_SECRET, `${zoneId}|${cluster.kind}|${cluster.target}`);
  const cacheKey = `verdict:${zoneId}:${fp}`;
  const cached = await env.KV.get<{ answers: Record<string, JevAnswer> }>(cacheKey, "json");
  if (cached) return { source: "cache", answers: cached.answers, verdict: toVerdict(cached.answers) };

  if (!jev) return { source: "rules", why: "no Jev key" };
  if (budget.callsLeftThisTick <= 0) return { source: "rules", why: "per-minute call cap reached" };
  const usage = await env.DB.prepare("SELECT jev_calls, est_cost FROM usage WHERE day = ?").bind(today())
    .first<{ jev_calls: number; est_cost: number }>();
  if ((usage?.jev_calls ?? 0) >= settings.jev.dailyCallCap) return { source: "rules", why: "daily call cap reached" };
  if ((usage?.est_cost ?? 0) >= settings.jev.dailySpendCap) return { source: "rules", why: "daily spend cap reached" };

  budget.callsLeftThisTick--;
  try {
    const res = await ask(jev, state, buildQuestions(settings.jev.customQuestions));
    const cost = (res.usage.input_tokens / 1e6) * settings.jev.pricePerMillionTokens;
    await env.DB.prepare(
      `INSERT INTO usage (day, jev_calls, jev_input_tokens, est_cost) VALUES (?, 1, ?, ?)
       ON CONFLICT(day) DO UPDATE SET jev_calls = jev_calls + 1, jev_input_tokens = jev_input_tokens + excluded.jev_input_tokens, est_cost = est_cost + excluded.est_cost`,
    ).bind(today(), res.usage.input_tokens, cost).run();
    await env.KV.put(cacheKey, JSON.stringify({ answers: res.answers }), { expirationTtl: Math.max(cacheTtl, 60) });
    return { source: "jev", answers: res.answers, verdict: toVerdict(res.answers), model: res.model };
  } catch (e) {
    const why = e instanceof JevError ? e.message : "Jev call failed";
    return { source: "rules", why };
  }
}
